# Generated by Django 4.0 on 2021-12-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to='posts'),
            preserve_default=False,
        ),
    ]
