# Generated by Django 4.0 on 2021-12-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_vote_delete_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
