# Generated by Django 4.0 on 2022-01-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_follow_delete_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
